### ISSUE TITLE
pass object to .ejs 

### ISSUE THREAD

**Issue by LuHua10** [carlsagan21/ejs-simple-loader#4]
Hi , I am trying to pass object to .ejs through ejs-simple-loader

if object has two property , will get error

`const testObj = {
    title: 'Fusion Net',
    name: 'Toby'
};`

but if object only have one property , will success

`const testObj = {
    name: 'Toby'
};`

```
new HtmlWebpackPlugin({
    template: 'ejs-simple-loader?data=' + ${JSON.stringify(testObj)} + '!./src/views/index.ejs', 
}),
```

get variable from .ejs
`<title> <%= JSON.parse(data).name %></title>`

error log

```
ERROR in ./~/ejs-simple-loader?data={"title":"Fusion Net","name":"Toby"}!./src/views/index.ejs
    Module build failed: TypeError: src/views/index.ejs:1
     >> 1| <% include ./header.ejs %>

esc is not a function
at rethrow (/Users/luhua/Project/FusionNet/node_modules/ejs-simple-loader/node_modules/ejs/lib/ejs.js:285:18)
at eval (eval at compile (/Users/luhua/Project/FusionNet/node_modules/ejs-simple-loader/node_modules/ejs/lib/ejs.js:524:12), <anonymous>:20:9)
at eval (eval at compile (/Users/luhua/Project/FusionNet/node_modules/ejs-simple-loader/node_modules/ejs/lib/ejs.js:524:12), <anonymous>:22:10)
at returnedFn (/Users/luhua/Project/FusionNet/node_modules/ejs-simple-loader/node_modules/ejs/lib/ejs.js:555:17)
at Object.ejsSimpleLoader (/Users/luhua/Project/FusionNet/node_modules/ejs-simple-loader/index.js:32:47)
```

thanks for your helping

**Comment by carlsagan21** [comment]
It's the 'ejs' package that is throwing your error, so I'm not sure what is the actual problem.
But if I were you, one thing I try first is using official syntex for `include`.
check <http://ejs.co/> `includes` section.

The example is even passing over an object itself to an included 'ejs'. so.. I hope this might help your problem.
```
<ul>
  <% users.forEach(function(user){ %>
    <%- include('user/show', {user: user}); %>
  <% }); %>
</ul>
```

If it did not worked, plz alert me again.
